spring.application.name=learn

# Database configuration
spring.datasource.url=jdbc:postgresql://db.qamuyzjqukipbtszromc.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=!LockedIN123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Server configuration
spring.main.web-application-type=servlet
server.error.include-message=always
